/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package research_emp;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import org.apache.hc.client5.http.classic.methods.HttpPost;
import org.apache.hc.client5.http.entity.mime.MultipartEntityBuilder;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.ContentType;
import org.apache.hc.core5.http.HttpEntity;
import org.apache.hc.core5.http.HttpStatus;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Geesara Ranathunga
 */
public class EMP_Reg extends javax.swing.JFrame {

    /**
     * Creates new form EMP_Reg
     */
    private static HttpURLConnection connection;
//    private HttpURLConnection httpConn;
    private DataOutputStream request;
    private final String boundary =  "*****";
    private final String crlf = "\r\n";
    private final String twoHyphens = "--";
    public String file_name;
    public String file_path;
    
    public EMP_Reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        first_namejTextField = new javax.swing.JTextField();
        addressjTextField = new javax.swing.JTextField();
        second_namejTextField = new javax.swing.JTextField();
        nic_numberjTextField = new javax.swing.JTextField();
        mobile_numberjTextField = new javax.swing.JTextField();
        emailjTextField = new javax.swing.JTextField();
        date_of_birthjTextField = new javax.swing.JTextField();
        nationalityjTextField = new javax.swing.JTextField();
        emergency_contactjTextField = new javax.swing.JTextField();
        first_namejLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        designationjTextField = new javax.swing.JTextField();
        departmentjTextField = new javax.swing.JTextField();
        epf_etf_numberjTextField = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Employee Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 11, -1, 67));

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 51));
        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 44, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("First Name :");
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 27, 167, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Second Name :");
        jLabel3.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 66, 167, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Address :");
        jLabel4.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 105, 167, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NIC Num :");
        jLabel5.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 144, 167, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mobile Num :");
        jLabel6.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 183, 167, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("E-mail :");
        jLabel7.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 222, 167, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nationalty :");
        jLabel8.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 261, 76, 20));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 272, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Date of Birth :");
        jLabel10.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 300, 167, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Sex :");
        jLabel11.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 339, 167, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Emergency Contact :");
        jLabel12.setMaximumSize(new java.awt.Dimension(20, 0));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 378, 167, 20));

        first_namejTextField.setBorder(null);
        first_namejTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                first_namejTextFieldMouseClicked(evt);
            }
        });
        first_namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_namejTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(first_namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 27, 312, 20));

        addressjTextField.setBorder(null);
        addressjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressjTextFieldMouseClicked(evt);
            }
        });
        addressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(addressjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 105, 312, 20));

        second_namejTextField.setBorder(null);
        second_namejTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                second_namejTextFieldMouseClicked(evt);
            }
        });
        second_namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_namejTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(second_namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 66, 312, 20));

        nic_numberjTextField.setBorder(null);
        nic_numberjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nic_numberjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(nic_numberjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 144, 312, 20));

        mobile_numberjTextField.setBorder(null);
        mobile_numberjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobile_numberjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(mobile_numberjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 183, 312, 20));

        emailjTextField.setBorder(null);
        emailjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(emailjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 222, 312, 20));

        date_of_birthjTextField.setBorder(null);
        date_of_birthjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_of_birthjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(date_of_birthjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 300, 312, 20));

        nationalityjTextField.setBorder(null);
        nationalityjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nationalityjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(nationalityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 261, 312, 20));

        emergency_contactjTextField.setBorder(null);
        emergency_contactjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emergency_contactjTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(emergency_contactjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 378, 312, 20));
        jPanel3.add(first_namejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 8, 310, 20));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 45, 310, 20));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 85, 310, 20));
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 125, 310, 20));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 165, 310, 20));
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 203, 310, 20));
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 243, 320, 20));
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 281, 310, 20));
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 318, 310, 20));
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 358, 310, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 340, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, 540, 430));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("ADD PHOTO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 55, 141, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Designation :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 176, 97, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Department :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 216, 92, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("EPF/ETF Num :");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 256, 97, -1));

        designationjTextField.setBorder(null);
        designationjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                designationjTextFieldMouseClicked(evt);
            }
        });
        jPanel4.add(designationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 176, 240, 20));

        departmentjTextField.setBorder(null);
        departmentjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentjTextFieldMouseClicked(evt);
            }
        });
        departmentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentjTextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(departmentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 216, 240, 20));

        epf_etf_numberjTextField.setBorder(null);
        epf_etf_numberjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epf_etf_numberjTextFieldMouseClicked(evt);
            }
        });
        jPanel4.add(epf_etf_numberjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 256, 240, 20));

        jTextField14.setBorder(null);
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 296, 240, 20));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 180, 120));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("username :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 296, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("password :");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, -1, -1));

        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel4.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 336, 240, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("retype password :");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, -1));

        jPasswordField2.setBorder(null);
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPanel4.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 376, 240, 20));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 156, 240, 20));
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 195, 240, 20));
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 235, 240, 20));
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 275, 240, 20));
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 315, 240, 20));
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 355, 240, 20));
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 19, 380, 430));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 370, 31));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 963, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        System.out.println("clicked");
        System.out.println("path: " +  file_path);
        System.out.println("name: " +  file_name);
        String first_name = first_namejTextField.getText();
        String second_name = second_namejTextField.getText();
        String address = addressjTextField.getText();
        String nic_number = nic_numberjTextField.getText();
        String mobile_number = mobile_numberjTextField.getText();
        String email = emailjTextField.getText();
        String nationality = nationalityjTextField.getText();
        String date_of_birth = date_of_birthjTextField.getText();
        String emergency_contact = emergency_contactjTextField.getText();
        String designation = designationjTextField.getText();
        String department = departmentjTextField.getText();
        String epf_etf_number = epf_etf_numberjTextField.getText();
        String username = jTextField14.getText();
        String password = new String(jPasswordField1.getPassword());
        String retype_password = new String(jPasswordField2.getPassword());
        String sex = jComboBox1.getSelectedItem().toString();

        hideValidation(first_namejTextField, first_namejLabel);
        hideValidation(second_namejTextField, jLabel21);
        hideValidation(addressjTextField, jLabel22);
        hideValidation(nic_numberjTextField, jLabel23);
        hideValidation(mobile_numberjTextField, jLabel24);
        hideValidation(emailjTextField, jLabel25);
        hideValidation(nationalityjTextField, jLabel26);
        hideValidation(date_of_birthjTextField, jLabel27);
        hideValidation(emergency_contactjTextField, jLabel29);
        hideValidation(jComboBox1, jLabel28);
        hideValidation(designationjTextField, jLabel13);
        hideValidation(departmentjTextField, jLabel17);
        hideValidation(epf_etf_numberjTextField, jLabel18);
        hideValidation(jTextField14, jLabel32);
        hideValidation(jPasswordField1, jLabel33);
        hideValidation(jPasswordField2, jLabel34);
        hideValidation(jButton1, jLabel36);
        
        CloseableHttpClient client = HttpClients.createDefault();
        HttpPost httpPost = new HttpPost("http://192.168.1.8:8000/api/employee?format=json");
        
        MultipartEntityBuilder builder = MultipartEntityBuilder.create();
        builder.addTextBody("username", username);
        builder.addTextBody("password", password);
        builder.addTextBody("retype_password", retype_password);
        builder.addTextBody("first_name", first_name);
        builder.addTextBody("second_name", second_name);
        builder.addTextBody("mobile_number", mobile_number);
        builder.addTextBody("nic_number", nic_number);
        builder.addTextBody("email", email);
        builder.addTextBody("nationality", nationality);
        builder.addTextBody("date_of_birth", date_of_birth);
        builder.addTextBody("sex", sex);
        builder.addTextBody("emergency_contact", emergency_contact);
        builder.addTextBody("designation", designation);
        builder.addTextBody("department", department);
        builder.addTextBody("epf_etf_number", epf_etf_number);
        builder.addTextBody("address", address);
        builder.addBinaryBody("photo", new File(file_path), ContentType.APPLICATION_OCTET_STREAM, file_name);
        
        HttpEntity multipart = builder.build();
        httpPost.setEntity(multipart);
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            HttpEntity entity = response.getEntity();

//            System.out.println(response.getReasonPhrase());
            String responseString= new String();
            responseString = EntityUtils.toString(entity, "UTF-8");
            client.close();
            
            String responseStatus = new String();
            responseStatus = response.getReasonPhrase();
            if ("Bad Request".equals(responseStatus)){
                System.out.println("if");
                JSONObject jsonObject = new JSONObject(responseString);
//                System.out.println(jsonObject.getJSONArray("photo"));
                JSONArray key = jsonObject.names ();
                for (int i = 0; i < key.length (); ++i) {
                   String keys = key.getString (i); 
                   JSONArray value = jsonObject.getJSONArray(keys);
//                   System.out.println("keys: " + keys);
//                   System.out.println("value: " + value);
                   
                   switch (keys) {
                       case "first_name":
                           showValidation(first_namejTextField, first_namejLabel, value.toString());
                           break;
                       case "second_name":
                           showValidation(second_namejTextField, jLabel21, value.toString());
                           break;
                       case "address":
                           showValidation(addressjTextField, jLabel22, value.toString());
                           break;
                       case "nic_number":
                           showValidation(nic_numberjTextField, jLabel23, value.toString());
                           break;
                       case "mobile_number":
                           showValidation(mobile_numberjTextField, jLabel24, value.toString());
                           break;
                       case "email":
                           showValidation(emailjTextField, jLabel25, value.toString());
                           break;
                       case "nationality":
                           showValidation(nationalityjTextField, jLabel26, value.toString());
                           break;
                       case "date_of_birth":
                           showValidation(date_of_birthjTextField, jLabel27, value.toString());
                           break;
                       case "emergency_contact":
                           showValidation(emergency_contactjTextField, jLabel29, value.toString());
                           break;
                       case "sex":
                           showValidation(jComboBox1, jLabel28, value.toString());
                           break;
                       case "designation":
                           showValidation(designationjTextField, jLabel13, value.toString());
                           break;
                       case "department":
                           showValidation(departmentjTextField, jLabel17, value.toString());
                           break;
                       case "epf_etf_number":
                           showValidation(epf_etf_numberjTextField, jLabel18, value.toString());
                           break;
                       case "username":
                           showValidation(jTextField14, jLabel32, value.toString());
                           break;
                       case "password":
                           showValidation(jPasswordField1, jLabel33, value.toString());
                           break;
                       case "retype_password":
                           showValidation(jPasswordField2, jLabel34, value.toString());
                           break;
                       case "photo":
                           showValidation(jButton1, jLabel36, value.toString());
                           break;
                   }
                }
            }
            else {
                 System.out.println("user created successfully");
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*
        try {
            JSONObject cred = new JSONObject();
            cred.put("username", "test");
            cred.put("password", "password");
            cred.put("retype_password", "password");
            cred.put("first_name", "first_name");
            cred.put("second_name", "second_name");
            cred.put("address", "address");
            cred.put("mobile_number", "+94770457788");
            cred.put("nic_number", "930350680V");
            cred.put("email", "kushan.gunasekera@gmail.com");
            cred.put("nationality", "LK");
            cred.put("date_of_birth", "1993-02-04");
            cred.put("sex", "Male");
            cred.put("emergency_contact", "+94770457788");
            cred.put("designation", "designation");
            cred.put("department", "department");
            cred.put("epf_etf_number", "001");
            cred.put("date", "2020-02-23");

            URL url = new URL("http://192.168.1.8:8000/api/employee?format=json");
            connection = (HttpURLConnection) url.openConnection();
            connection.setConnectTimeout(5000);
            connection.setUseCaches(false);
            connection.setRequestProperty("Connection", "Keep-Alive");
            connection.setRequestProperty("Content-Type", "application/json; charset=UTF-8");
            connection.setRequestProperty("Cache-Control", "no-cache");
            connection.setRequestProperty("Content-Type", "multipart/form-data;boundary=" + this.boundary);
            connection.setDoOutput(true);
            connection.setDoInput(true);
            connection.setReadTimeout(5000);
            connection.setRequestMethod("POST");

            OutputStream os = connection.getOutputStream();
//            os.write(b);
            os.write(cred.toString().getBytes("UTF-8"));
            os.close();

            int status = connection.getResponseCode();
            System.err.println(status);

            BufferedReader reader;
            String line;
            StringBuffer responseContent = new StringBuffer();

            if (status > 299){
                reader = new BufferedReader(new InputStreamReader(connection.getErrorStream()));
                while((line = reader.readLine()) != null){
                    responseContent.append(line);
                }
                reader.close();
            } else {
                reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                while((line = reader.readLine()) != null){
                    responseContent.append(line);
                }
                reader.close();
            }

            System.out.println(responseContent.toString());

        } catch (MalformedURLException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(EMP_Reg.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            connection.disconnect();
        }
        */

        //        HttpClient client = HttpClient.newHttpClient();
        //        HttpRequest request = HttpRequest.newBuilder().uri(URI.create("http://192.168.1.8:8000/api/employee?format=json")).build();
        //        client.sendAsync(request, HttpResponse.BodyHandlers.ofString())
        //                .thenApply(HttpResponse::body)
        //                .thenAccept(System.out::println)
        //                .join();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void showValidation(JTextField textField, JLabel label, String value){
        System.out.println("I just got executed! 1");
        textField.setBorder(new LineBorder(Color.RED, 2));
        showValidationLabel(label, value);
    }
    
    public void showValidation(JComboBox comboBox, JLabel label, String value){
        System.out.println("I just got executed! 2");
        comboBox.setBorder(new LineBorder(Color.RED, 2));
        showValidationLabel(label, value);
    }
    
    public void showValidation(JPasswordField passwordField, JLabel label, String value){
        System.out.println("I just got executed! 2");
        passwordField.setBorder(new LineBorder(Color.RED, 2));
        showValidationLabel(label, value);
    }
    
    public void showValidation(JButton button, JLabel label, String value){
        System.out.println("I just got executed! 2");
        button.setBorder(new LineBorder(Color.RED, 2));
        showValidationLabel(label, value);
    }
    
    public void showValidationLabel(JLabel label, String value){
        label.setText(value.toString());
        label.setForeground(Color.red);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setVerticalAlignment(SwingConstants.CENTER);
    }
    
    public void hideValidation(JTextField textField, JLabel label){
        System.out.println("I just got executed! hide");
        textField.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        showValidationLabel(label, "");
    }
    
    public void hideValidation(JComboBox comboBox, JLabel label){
        System.out.println("I just got executed! hide");
        comboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        showValidationLabel(label, "");
    }
    
    public void hideValidation(JPasswordField passwordField, JLabel label){
        System.out.println("I just got executed! hide");
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        showValidationLabel(label, "");
    }
    
    public void hideValidation(JButton button, JLabel label){
        System.out.println("I just got executed! hide");
        button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        showValidationLabel(label, "");
    }
    
    
    
    private void departmentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentjTextFieldActionPerformed

    private void second_namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_second_namejTextFieldActionPerformed

    private void addressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextFieldActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Main_menu m6 = new Main_menu();
        m6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("add photo");
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        file_name = file.getName();
        file_path = file.getAbsolutePath();
        System.out.println("path: " +  file_path);
        System.out.println("name: " +  file_name);
        ImageIcon icon = new ImageIcon(file_path);
        jLabel19.setIcon(icon);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void first_namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_namejTextFieldActionPerformed

    private void first_namejTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_first_namejTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(first_namejTextField, first_namejLabel);
    }//GEN-LAST:event_first_namejTextFieldMouseClicked

    private void second_namejTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_second_namejTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(second_namejTextField, jLabel21);
    }//GEN-LAST:event_second_namejTextFieldMouseClicked

    private void addressjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(addressjTextField, jLabel22);
    }//GEN-LAST:event_addressjTextFieldMouseClicked

    private void nic_numberjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nic_numberjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(nic_numberjTextField, jLabel23);
    }//GEN-LAST:event_nic_numberjTextFieldMouseClicked

    private void mobile_numberjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_numberjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(mobile_numberjTextField, jLabel24);
    }//GEN-LAST:event_mobile_numberjTextFieldMouseClicked

    private void emailjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(emailjTextField, jLabel25);
    }//GEN-LAST:event_emailjTextFieldMouseClicked

    private void nationalityjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nationalityjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(nationalityjTextField, jLabel26);
    }//GEN-LAST:event_nationalityjTextFieldMouseClicked

    private void date_of_birthjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_of_birthjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(date_of_birthjTextField, jLabel27);
    }//GEN-LAST:event_date_of_birthjTextFieldMouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        hideValidation(jComboBox1, jLabel28);
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void emergency_contactjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergency_contactjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(emergency_contactjTextField, jLabel29);
    }//GEN-LAST:event_emergency_contactjTextFieldMouseClicked

    private void designationjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designationjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(designationjTextField, jLabel13);
    }//GEN-LAST:event_designationjTextFieldMouseClicked

    private void departmentjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(departmentjTextField, jLabel17);
    }//GEN-LAST:event_departmentjTextFieldMouseClicked

    private void epf_etf_numberjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epf_etf_numberjTextFieldMouseClicked
        // TODO add your handling code here:
        hideValidation(epf_etf_numberjTextField, jLabel18);
    }//GEN-LAST:event_epf_etf_numberjTextFieldMouseClicked

    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
        // TODO add your handling code here:
        hideValidation(jTextField14, jLabel32);
    }//GEN-LAST:event_jTextField14MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        hideValidation(jPasswordField1, jLabel33);
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        hideValidation(jPasswordField2, jLabel34);
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        hideValidation(jButton1, jLabel36);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMP_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMP_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMP_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMP_Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMP_Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JTextField date_of_birthjTextField;
    private javax.swing.JTextField departmentjTextField;
    private javax.swing.JTextField designationjTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField emergency_contactjTextField;
    private javax.swing.JTextField epf_etf_numberjTextField;
    private javax.swing.JLabel first_namejLabel;
    private javax.swing.JTextField first_namejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField mobile_numberjTextField;
    private javax.swing.JTextField nationalityjTextField;
    private javax.swing.JTextField nic_numberjTextField;
    private javax.swing.JTextField second_namejTextField;
    // End of variables declaration//GEN-END:variables
}
